### ISSUE TITLE
Define Workflow Run RO-Crate profile

### ISSUE THREAD

**Issue by stain** [inab/WfExS-backend#11]
See [WfExS possible RO-Crate profiles](https://docs.google.com/document/d/1ALo0yQITwrzvmRPGzNqdG3zstr0XZ1FSliBjU2CNNwY/edit#) captured by  @lrodrin @jmfernandez

We should gather some example outputs and first look how far we get with using https://www.researchobject.org/ro-crate/1.1/provenance.html

Also see https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles.html

**Comment by jmfernandez** [comment]
As of 0.9.0 tag (f2c6fed0308a92436b35b6fba4ec13926046fa57) most of the profile is implemented. WfExS-backend now is also able to generate materialized crates, where the workflow, inputs, containers (and outputs for retrospective cases) are included. Some semantic descriptions and all the metrics are still left, and some details like including the graphical representation of the executed workflow.
