### ISSUE TITLE
Error when adding dot file to output RO crate

### ISSUE THREAD

**Issue by wkwi2r** [inab/WfExS-backend#137]
I'm running a local installation of WfExS with python 3.12.3.

The workflow file is as follows:

```
workflow_id: github:inab/hello-workflows/f34b1c42b9b3789e9e27d0d8742eedc867b6525a/cwl/hello-workflow-external.cwl
workflow_config:
  secure: false
  containerType: docker
params:
  an_input:
    c-l-a-s-s: File
    url: github:inab/hello-workflows/b0afc5871c6fdbd66576fcc5a3813ea49aca5104/cwl/hello.yml
environment:
  SECRET_VARIABLE: "The secret content"
outputs:
  hello_output:
    c-l-a-s-s: File
```

I encountered the following exception:

```
Traceback (most recent call last):
  File "/home/wfexs/WfExS_python_build/WfExS-backend/WfExS-backend.py", line 22, in <module>
    main()
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/__main__.py", line 1769, in main
    wfInstance.createResultsResearchObject(
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/workflow.py", line 5561, in createResultsResearchObject
    wrroc.addWorkflowExecution(
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/ro_crate.py", line 2635, in addWorkflowExecution
    dot_file = WorkflowDiagram(
               ^^^^^^^^^^^^^^^^
  File "/home/wfexs/WfExS_python_build/WfExS-backend/wfexs_backend/ro_crate.py", line 359, in __init__
    raise ValueError("if provided, dest_path must be relative")
ValueError: if provided, dest_path must be relative
```

I've done some tracing and found that `stagedExec.diagram` is assigned to `dest_path` and is an absolute path. I'm unable to find where its value is initialised. One solution I found is to use `stagedExec.diagram.relative_to(self.work_dir).as_posix()` to extract out the relative path and assigned to `dest_path`.

Appreciate your help to resolve with the correct solution.

**Comment by jmfernandez** [comment]
Thanks for the feedback! I could reproduce the bug. It seems I did not perform enough testing in RO-Crate generation when I transitioned the code from path handling using strings to path handling using `pathlib.Path` instances.

**Comment by jmfernandez** [comment]
I have written a fix, tested it and merged it to main branch. Could you try installing locally the main branch and repeating the steps, please?

**Comment by wkwi2r** [comment]
> I have written a fix, tested it and merged it to main branch. Could you try installing locally the main branch and repeating the steps, please?

@jmfernandez  latest commits work great, thanks 👍
